# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bessel_layer_simulation <- function(x, y, s, t, a) {
    .Call(`_layeredBB_bessel_layer_simulation`, x, y, s, t, a)
}

return_list <- function(x, y, a, b) {
    .Call(`_layeredBB_return_list`, x, y, a, b)
}

M_function <- function(a, x, y, s, t) {
    .Call(`_layeredBB_M_function`, a, x, y, s, t)
}

min_sampler <- function(x, y, s, t, low_bound, up_bound) {
    .Call(`_layeredBB_min_sampler`, x, y, s, t, low_bound, up_bound)
}

min_Bessel_bridge_sampler <- function(x, y, s, t, min, tau, q) {
    .Call(`_layeredBB_min_Bessel_bridge_sampler`, x, y, s, t, min, tau, q)
}

min_Bessel_bridge_path_sampler <- function(x, y, s, t, min, tau, times) {
    .Call(`_layeredBB_min_Bessel_bridge_path_sampler`, x, y, s, t, min, tau, times)
}

max_sampler <- function(x, y, s, t, low_bound, up_bound) {
    .Call(`_layeredBB_max_sampler`, x, y, s, t, low_bound, up_bound)
}

max_Bessel_bridge_sampler <- function(x, y, s, t, max, tau, q) {
    .Call(`_layeredBB_max_Bessel_bridge_sampler`, x, y, s, t, max, tau, q)
}

max_Bessel_bridge_path_sampler <- function(x, y, s, t, max, tau, times) {
    .Call(`_layeredBB_max_Bessel_bridge_path_sampler`, x, y, s, t, max, tau, times)
}

sigma_bar <- function(j, x, y, s, t, l, v) {
    .Call(`_layeredBB_sigma_bar`, j, x, y, s, t, l, v)
}

sigma <- function(j, x, y, s, t, l, v) {
    .Call(`_layeredBB_sigma`, j, x, y, s, t, l, v)
}

phi_bar <- function(j, x, y, s, t, l, v) {
    .Call(`_layeredBB_phi_bar`, j, x, y, s, t, l, v)
}

phi <- function(j, x, y, s, t, l, v) {
    .Call(`_layeredBB_phi`, j, x, y, s, t, l, v)
}

psi <- function(j, x, y, s, t, min, v) {
    .Call(`_layeredBB_psi`, j, x, y, s, t, min, v)
}

chi <- function(j, x, y, s, t, min, v) {
    .Call(`_layeredBB_chi`, j, x, y, s, t, min, v)
}

calc_SgammaK_intervals <- function(k, x, y, s, t, l, v) {
    .Call(`_layeredBB_calc_SgammaK_intervals`, k, x, y, s, t, l, v)
}

calc_SdeltaK_1_intervals <- function(k, x, y, s, t, min, v) {
    .Call(`_layeredBB_calc_SdeltaK_1_intervals`, k, x, y, s, t, min, v)
}

calc_SdeltaK_2_intervals <- function(k, x, y, s, t, min, v) {
    .Call(`_layeredBB_calc_SdeltaK_2_intervals`, k, x, y, s, t, min, v)
}

calc_SdeltaK_intervals <- function(k, x, y, s, t, min, v) {
    .Call(`_layeredBB_calc_SdeltaK_intervals`, k, x, y, s, t, min, v)
}

product_vector_elements <- function(vect) {
    .Call(`_layeredBB_product_vector_elements`, vect)
}

gamma_coin <- function(x, y, s, t, l, v, k) {
    .Call(`_layeredBB_gamma_coin`, x, y, s, t, l, v, k)
}

gamma_coin_intervals <- function(x, y, s, t, l, v, k) {
    .Call(`_layeredBB_gamma_coin_intervals`, x, y, s, t, l, v, k)
}

delta_coin <- function(x, y, s, t, min, v, k) {
    .Call(`_layeredBB_delta_coin`, x, y, s, t, min, v, k)
}

delta_coin_intervals <- function(x, y, s, t, min, v, k) {
    .Call(`_layeredBB_delta_coin_intervals`, x, y, s, t, min, v, k)
}

inv_gauss_sampler <- function(mu, lambda) {
    .Call(`_layeredBB_inv_gauss_sampler`, mu, lambda)
}

find_max <- function(vect) {
    .Call(`_layeredBB_find_max`, vect)
}

find_min <- function(vect) {
    .Call(`_layeredBB_find_min`, vect)
}

layered_brownian_bridge <- function(x, y, s, t, a, l, times) {
    .Call(`_layeredBB_layered_brownian_bridge`, x, y, s, t, a, l, times)
}

